### PR TITLE
Tested with Django 2.2 LTS

### PR DESCRIPTION
**Pull request by ribeiroti**

### CODE REVIEW

**Comment by jordiecometrica** [comment]
If I'm reading this right, we're not currently running the tests on 3.6 at all, so coverage didn't run on Django 2.2 either?

https://coveralls.io/builds/23153266

**Comment by ribeiroti** [comment]
> If I'm reading this right, we're not currently running the tests on 3.6 at all, so coverage didn't run on Django 2.2 either?
> 
> https://coveralls.io/builds/23153266

Well.. I don't know... I'm just using it on py 3.6 and django 2.2 and works. Django 2.1 and 2.2 are pretty similar, but 2.2 is a long term support version.

**Comment by jordiecometrica** [comment]
It appears the tests actually failed on Python 3.6:

https://travis-ci.org/ecometrica/django-multisite/jobs/527392239

**Comment by ribeiroti** [comment]
Yes, maybe I don't get the error in my env because I'm not using sqlite

`packages/django/db/backends/sqlite3/base.py", line 66, in <module>
    check_sqlite_version()
  File "/home/travis/build/ecometrica/django-multisite/.tox/py36-django2.2/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.8.2).`

**Comment by jordiecometrica** [comment]
Looks like it's just coverage. Further below the tests actually pass.

Good enough for me.

**Comment by jordiecometrica** [comment]
Thanks for the changes.

**Comment by ribeiroti** [comment]
No. I thank you. I'm just enjoying the package. Regards!

**Pull request merged**
