### PR TITLE
method name fix

### LINKED ISSUE #61: AliasInline should override `get_queryset`, not `queryset`
According to django docs ModelAdmin has `get_queryset` method, not `queryset`

https://github.com/ecometrica/django-multisite/blob/e97e8d405f1456aed68d9c2e052a8296f2fcbc90/multisite/admin.py#L31

### PR DESCRIPTION
**Pull request by vit-ivanov**
closes #61

### CODE REVIEW

**Comment by pauricthelodger** [comment]
Hey @vit-ivanov 

Thanks for spotting this one, `queryset` got removed in ~1.6! =O

Would you mind updating the one on line 96 as well while you're in there? =)

**Comment by vit-ivanov** [comment]
Lol, sure :)

**Comment by jordiecometrica** [comment]
lgtm, Django 1.8 is our minimum requirement.

**Comment by pauricthelodger** [comment]
Thanks @vit-ivanov!

**Pull request merged**
